### ISSUE TITLE
No runtime set

### ISSUE THREAD

**Issue by leehadassin** [codyc1515/homebridge-orbit-bhyve#16] opened 2019-12-13 15:12 UTC
Excellent work. Thanks

I have the B-hyve Smart Indoor Sprinkler Timer 4 Station Model.
I am pretty sure my config is correct (I have 4 zones and set "zones": 4 in the config).

I am unable to turn on zones from home app (switches show waiting indefinitely) but they do show as running when I turn on from the b-hyve app and view them in home (they show running with the correct countdown time)

Debug shows:

Found sprinkler 'Sprinklers' with id xxxxxxxxxxxxxx and state **null**

 Message sent:  {"event":"change_mode","device_id":"xxxxxxxxxxxxxxxxx","stations":[{"station":1,"run_time":**NaN**}],"mode":"manual"}

**Comment by leehadassin** [comment] 2019-12-13 23:05
Sorry realised this might be a repeat of #12

**Comment by leehadassin** [comment] 2020-02-25 13:42
Further testing shows when I run a zone in manual mode from the the orbit app and then look at the debug it shows

Found sprinkler 'Sprinklers' with id xxxxxxxxxxxxxx and state **[object Object]**

also turning off the zone from home app when it is currently running does work

**Comment by codyc1515** [comment] 2020-05-19 05:54
Looks like duplicate of #13

**Closed as completed** 2020-05-19 06:13 UTC
